### ISSUE TITLE
Fix for view "Analýza cizinců ve světě" - year of dataset is missing

### ISSUE THREAD

**Issue by zruzicka** [zruzicka/HackujStat.cz_2018#1]
Presented dataset "*Analýza cizinců ve světě*" miss any information about year of origin.

Dataset needs to be presented together with year which is relevant for these data.

Presented form can be for example "**Analýza cizinců ve světě (2017)**"

**Comment by jindrichmynarz** [comment]
You can find the year of origin in the column `rok`.

**Comment by zruzicka** [comment]
@jindrichmynarz Thank you for your comment. I am just still not able to see it yet (please see pictures below). Could you please post some screenshot with column *rok* here?
![image](https://user-images.githubusercontent.com/18603531/46575625-eea8b780-c9b8-11e8-9b1c-56060ae9ddb1.png)
![image](https://user-images.githubusercontent.com/18603531/46575644-65de4b80-c9b9-11e8-8aa2-0a0c5b7e1615.png)

I believe we can also invite Martin and assign him that label modification as he agreed about minor updates in previous email communication.

**Comment by zruzicka** [comment]
An invitation for https://github.com/mattesCZ just has been sent. :)

**Comment by zruzicka** [comment]
I am really sorry, I posted wrong view name. The issue with missing year of dataset is for "Analýza cizinců ve světě", but not for "Analýza cizinců v ČR" as I described before. Issue title and description just updated. Sorry for my previous fault. ;)

**Comment by jindrichmynarz** [comment]
I misunderstood you question. I thought you reported years as missing in the data, not in the view.

**Comment by mattesCZ** [comment]
There is a fixed filter in `oecd_stock_metric` to display only data from 2016. I'll update the view title to "Analýza cizinců ve světě (2016)"

**Comment by zruzicka** [comment]
Great, thank you! Yes, "Analýza cizinců ve světě (2016)" is the correct title.
